// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: tgbot/v1/tgbot.proto

package tgbotv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на отправку кода сброса пароля
type SendPasswordResetCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"` // Telegram ID пользователя
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                // Код сброса пароля
	TtlSeconds    int32                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // Время жизни кода (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPasswordResetCodeRequest) Reset() {
	*x = SendPasswordResetCodeRequest{}
	mi := &file_tgbot_v1_tgbot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPasswordResetCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPasswordResetCodeRequest) ProtoMessage() {}

func (x *SendPasswordResetCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgbot_v1_tgbot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPasswordResetCodeRequest.ProtoReflect.Descriptor instead.
func (*SendPasswordResetCodeRequest) Descriptor() ([]byte, []int) {
	return file_tgbot_v1_tgbot_proto_rawDescGZIP(), []int{0}
}

func (x *SendPasswordResetCodeRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *SendPasswordResetCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SendPasswordResetCodeRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// Запрос на отправку кода подтверждения
type SendVerificationCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Purpose       string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"` // signup, change_phone и т.д.
	TtlSeconds    int32                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerificationCodeRequest) Reset() {
	*x = SendVerificationCodeRequest{}
	mi := &file_tgbot_v1_tgbot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerificationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationCodeRequest) ProtoMessage() {}

func (x *SendVerificationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgbot_v1_tgbot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationCodeRequest.ProtoReflect.Descriptor instead.
func (*SendVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return file_tgbot_v1_tgbot_proto_rawDescGZIP(), []int{1}
}

func (x *SendVerificationCodeRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *SendVerificationCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SendVerificationCodeRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *SendVerificationCodeRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// Запрос на отправку произвольного уведомления
type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_tgbot_v1_tgbot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgbot_v1_tgbot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_tgbot_v1_tgbot_proto_rawDescGZIP(), []int{2}
}

func (x *SendNotificationRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *SendNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_tgbot_v1_tgbot_proto protoreflect.FileDescriptor

const file_tgbot_v1_tgbot_proto_rawDesc = "" +
	"\n" +
	"\x14tgbot/v1/tgbot.proto\x12\btgbot.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x94\x01\n" +
	"\x1cSendPasswordResetCodeRequest\x12(\n" +
	"\vtelegram_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"telegramId\x12\x1d\n" +
	"\x04code\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18\fR\x04code\x12+\n" +
	"\vttl_seconds\x18\x04 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\x90\x1c(<R\n" +
	"ttlSeconds\"\xca\x01\n" +
	"\x1bSendVerificationCodeRequest\x12(\n" +
	"\vtelegram_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"telegramId\x12\x1d\n" +
	"\x04code\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18\fR\x04code\x125\n" +
	"\apurpose\x18\x03 \x01(\tB\x1b\xfaB\x18r\x16R\x06signupR\fchange_phoneR\apurpose\x12+\n" +
	"\vttl_seconds\x18\x04 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\x90\x1c(<R\n" +
	"ttlSeconds\"i\n" +
	"\x17SendNotificationRequest\x12(\n" +
	"\vtelegram_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"telegramId\x12$\n" +
	"\amessage\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80 R\amessage2\x89\x03\n" +
	"\fTgBotService\x12\x83\x01\n" +
	"\x15SendPasswordResetCode\x12&.tgbot.v1.SendPasswordResetCodeRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/tg/send-password-reset-code\x12\x7f\n" +
	"\x14SendVerificationCode\x12%.tgbot.v1.SendVerificationCodeRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/tg/send-verification-code\x12r\n" +
	"\x10SendNotification\x12!.tgbot.v1.SendNotificationRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/tg/send-notificationB9Z7github.com/Anabol1ks/rentAdvisor-proto/tgbot/v1;tgbotv1b\x06proto3"

var (
	file_tgbot_v1_tgbot_proto_rawDescOnce sync.Once
	file_tgbot_v1_tgbot_proto_rawDescData []byte
)

func file_tgbot_v1_tgbot_proto_rawDescGZIP() []byte {
	file_tgbot_v1_tgbot_proto_rawDescOnce.Do(func() {
		file_tgbot_v1_tgbot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tgbot_v1_tgbot_proto_rawDesc), len(file_tgbot_v1_tgbot_proto_rawDesc)))
	})
	return file_tgbot_v1_tgbot_proto_rawDescData
}

var file_tgbot_v1_tgbot_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tgbot_v1_tgbot_proto_goTypes = []any{
	(*SendPasswordResetCodeRequest)(nil), // 0: tgbot.v1.SendPasswordResetCodeRequest
	(*SendVerificationCodeRequest)(nil),  // 1: tgbot.v1.SendVerificationCodeRequest
	(*SendNotificationRequest)(nil),      // 2: tgbot.v1.SendNotificationRequest
	(*emptypb.Empty)(nil),                // 3: google.protobuf.Empty
}
var file_tgbot_v1_tgbot_proto_depIdxs = []int32{
	0, // 0: tgbot.v1.TgBotService.SendPasswordResetCode:input_type -> tgbot.v1.SendPasswordResetCodeRequest
	1, // 1: tgbot.v1.TgBotService.SendVerificationCode:input_type -> tgbot.v1.SendVerificationCodeRequest
	2, // 2: tgbot.v1.TgBotService.SendNotification:input_type -> tgbot.v1.SendNotificationRequest
	3, // 3: tgbot.v1.TgBotService.SendPasswordResetCode:output_type -> google.protobuf.Empty
	3, // 4: tgbot.v1.TgBotService.SendVerificationCode:output_type -> google.protobuf.Empty
	3, // 5: tgbot.v1.TgBotService.SendNotification:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tgbot_v1_tgbot_proto_init() }
func file_tgbot_v1_tgbot_proto_init() {
	if File_tgbot_v1_tgbot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tgbot_v1_tgbot_proto_rawDesc), len(file_tgbot_v1_tgbot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tgbot_v1_tgbot_proto_goTypes,
		DependencyIndexes: file_tgbot_v1_tgbot_proto_depIdxs,
		MessageInfos:      file_tgbot_v1_tgbot_proto_msgTypes,
	}.Build()
	File_tgbot_v1_tgbot_proto = out.File
	file_tgbot_v1_tgbot_proto_goTypes = nil
	file_tgbot_v1_tgbot_proto_depIdxs = nil
}
