// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: auth/v1/auth.proto

package authv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateTelegramVerificationCodeRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *CreateTelegramVerificationCodeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTelegramVerificationCodeRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// CreateTelegramVerificationCodeRequestMultiError, or nil if none found.
func (m *CreateTelegramVerificationCodeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTelegramVerificationCodeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTelegramId() <= 0 {
		err := CreateTelegramVerificationCodeRequestValidationError{
			field:  "TelegramId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := VerificationPurpose_name[int32(m.GetPurpose())]; !ok {
		err := CreateTelegramVerificationCodeRequestValidationError{
			field:  "Purpose",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_CreateTelegramVerificationCodeRequest_Phone_Pattern.MatchString(m.GetPhone()) {
		err := CreateTelegramVerificationCodeRequestValidationError{
			field:  "Phone",
			reason: "value does not match regex pattern \"^\\\\+[1-9]\\\\d{1,14}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetTtlSeconds(); val < 60 || val > 3600 {
		err := CreateTelegramVerificationCodeRequestValidationError{
			field:  "TtlSeconds",
			reason: "value must be inside range [60, 3600]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateTelegramVerificationCodeRequestMultiError(errors)
	}

	return nil
}

// CreateTelegramVerificationCodeRequestMultiError is an error wrapping
// multiple validation errors returned by
// CreateTelegramVerificationCodeRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateTelegramVerificationCodeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTelegramVerificationCodeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTelegramVerificationCodeRequestMultiError) AllErrors() []error { return m }

// CreateTelegramVerificationCodeRequestValidationError is the validation error
// returned by CreateTelegramVerificationCodeRequest.Validate if the
// designated constraints aren't met.
type CreateTelegramVerificationCodeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTelegramVerificationCodeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTelegramVerificationCodeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTelegramVerificationCodeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTelegramVerificationCodeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTelegramVerificationCodeRequestValidationError) ErrorName() string {
	return "CreateTelegramVerificationCodeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTelegramVerificationCodeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTelegramVerificationCodeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTelegramVerificationCodeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTelegramVerificationCodeRequestValidationError{}

var _CreateTelegramVerificationCodeRequest_Phone_Pattern = regexp.MustCompile("^\\+[1-9]\\d{1,14}$")

// Validate checks the field values on CreateTelegramVerificationCodeResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *CreateTelegramVerificationCodeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// CreateTelegramVerificationCodeResponse with the rules defined in the proto
// definition for this message. If any rules are violated, the result is a
// list of violation errors wrapped in
// CreateTelegramVerificationCodeResponseMultiError, or nil if none found.
func (m *CreateTelegramVerificationCodeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTelegramVerificationCodeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetCode()); l < 4 || l > 12 {
		err := CreateTelegramVerificationCodeResponseValidationError{
			field:  "Code",
			reason: "value length must be between 4 and 12 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetExpiresAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateTelegramVerificationCodeResponseValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateTelegramVerificationCodeResponseValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpiresAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateTelegramVerificationCodeResponseValidationError{
				field:  "ExpiresAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateTelegramVerificationCodeResponseMultiError(errors)
	}

	return nil
}

// CreateTelegramVerificationCodeResponseMultiError is an error wrapping
// multiple validation errors returned by
// CreateTelegramVerificationCodeResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateTelegramVerificationCodeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTelegramVerificationCodeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTelegramVerificationCodeResponseMultiError) AllErrors() []error { return m }

// CreateTelegramVerificationCodeResponseValidationError is the validation
// error returned by CreateTelegramVerificationCodeResponse.Validate if the
// designated constraints aren't met.
type CreateTelegramVerificationCodeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTelegramVerificationCodeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTelegramVerificationCodeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTelegramVerificationCodeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTelegramVerificationCodeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTelegramVerificationCodeResponseValidationError) ErrorName() string {
	return "CreateTelegramVerificationCodeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTelegramVerificationCodeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTelegramVerificationCodeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTelegramVerificationCodeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTelegramVerificationCodeResponseValidationError{}

// Validate checks the field values on ConfirmTelegramVerificationRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ConfirmTelegramVerificationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConfirmTelegramVerificationRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ConfirmTelegramVerificationRequestMultiError, or nil if none found.
func (m *ConfirmTelegramVerificationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ConfirmTelegramVerificationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTelegramId() <= 0 {
		err := ConfirmTelegramVerificationRequestValidationError{
			field:  "TelegramId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := VerificationPurpose_name[int32(m.GetPurpose())]; !ok {
		err := ConfirmTelegramVerificationRequestValidationError{
			field:  "Purpose",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetCode()); l < 4 || l > 12 {
		err := ConfirmTelegramVerificationRequestValidationError{
			field:  "Code",
			reason: "value length must be between 4 and 12 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_ConfirmTelegramVerificationRequest_Phone_Pattern.MatchString(m.GetPhone()) {
		err := ConfirmTelegramVerificationRequestValidationError{
			field:  "Phone",
			reason: "value does not match regex pattern \"^\\\\+[1-9]\\\\d{1,14}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ConfirmTelegramVerificationRequestMultiError(errors)
	}

	return nil
}

// ConfirmTelegramVerificationRequestMultiError is an error wrapping multiple
// validation errors returned by
// ConfirmTelegramVerificationRequest.ValidateAll() if the designated
// constraints aren't met.
type ConfirmTelegramVerificationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConfirmTelegramVerificationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConfirmTelegramVerificationRequestMultiError) AllErrors() []error { return m }

// ConfirmTelegramVerificationRequestValidationError is the validation error
// returned by ConfirmTelegramVerificationRequest.Validate if the designated
// constraints aren't met.
type ConfirmTelegramVerificationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfirmTelegramVerificationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfirmTelegramVerificationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfirmTelegramVerificationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfirmTelegramVerificationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfirmTelegramVerificationRequestValidationError) ErrorName() string {
	return "ConfirmTelegramVerificationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ConfirmTelegramVerificationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConfirmTelegramVerificationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfirmTelegramVerificationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfirmTelegramVerificationRequestValidationError{}

var _ConfirmTelegramVerificationRequest_Phone_Pattern = regexp.MustCompile("^\\+[1-9]\\d{1,14}$")

// Validate checks the field values on ConfirmTelegramVerificationResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ConfirmTelegramVerificationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConfirmTelegramVerificationResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ConfirmTelegramVerificationResponseMultiError, or nil if none found.
func (m *ConfirmTelegramVerificationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ConfirmTelegramVerificationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Phone

	// no validation rules for Verified

	if len(errors) > 0 {
		return ConfirmTelegramVerificationResponseMultiError(errors)
	}

	return nil
}

// ConfirmTelegramVerificationResponseMultiError is an error wrapping multiple
// validation errors returned by
// ConfirmTelegramVerificationResponse.ValidateAll() if the designated
// constraints aren't met.
type ConfirmTelegramVerificationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConfirmTelegramVerificationResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConfirmTelegramVerificationResponseMultiError) AllErrors() []error { return m }

// ConfirmTelegramVerificationResponseValidationError is the validation error
// returned by ConfirmTelegramVerificationResponse.Validate if the designated
// constraints aren't met.
type ConfirmTelegramVerificationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfirmTelegramVerificationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfirmTelegramVerificationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfirmTelegramVerificationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfirmTelegramVerificationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfirmTelegramVerificationResponseValidationError) ErrorName() string {
	return "ConfirmTelegramVerificationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ConfirmTelegramVerificationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConfirmTelegramVerificationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfirmTelegramVerificationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfirmTelegramVerificationResponseValidationError{}

// Validate checks the field values on RegisterRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RegisterRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterRequestMultiError, or nil if none found.
func (m *RegisterRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_RegisterRequest_Phone_Pattern.MatchString(m.GetPhone()) {
		err := RegisterRequestValidationError{
			field:  "Phone",
			reason: "value does not match regex pattern \"^\\\\+[1-9]\\\\d{1,14}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetPassword()); l < 8 || l > 64 {
		err := RegisterRequestValidationError{
			field:  "Password",
			reason: "value length must be between 8 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RegisterRequestMultiError(errors)
	}

	return nil
}

// RegisterRequestMultiError is an error wrapping multiple validation errors
// returned by RegisterRequest.ValidateAll() if the designated constraints
// aren't met.
type RegisterRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterRequestMultiError) AllErrors() []error { return m }

// RegisterRequestValidationError is the validation error returned by
// RegisterRequest.Validate if the designated constraints aren't met.
type RegisterRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterRequestValidationError) ErrorName() string { return "RegisterRequestValidationError" }

// Error satisfies the builtin error interface
func (e RegisterRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterRequestValidationError{}

var _RegisterRequest_Phone_Pattern = regexp.MustCompile("^\\+[1-9]\\d{1,14}$")

// Validate checks the field values on RegisterResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RegisterResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterResponseMultiError, or nil if none found.
func (m *RegisterResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Phone

	if len(errors) > 0 {
		return RegisterResponseMultiError(errors)
	}

	return nil
}

// RegisterResponseMultiError is an error wrapping multiple validation errors
// returned by RegisterResponse.ValidateAll() if the designated constraints
// aren't met.
type RegisterResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterResponseMultiError) AllErrors() []error { return m }

// RegisterResponseValidationError is the validation error returned by
// RegisterResponse.Validate if the designated constraints aren't met.
type RegisterResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterResponseValidationError) ErrorName() string { return "RegisterResponseValidationError" }

// Error satisfies the builtin error interface
func (e RegisterResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterResponseValidationError{}

// Validate checks the field values on LoginRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LoginRequestMultiError, or
// nil if none found.
func (m *LoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_LoginRequest_Phone_Pattern.MatchString(m.GetPhone()) {
		err := LoginRequestValidationError{
			field:  "Phone",
			reason: "value does not match regex pattern \"^\\\\+[1-9]\\\\d{1,14}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetPassword()); l < 8 || l > 64 {
		err := LoginRequestValidationError{
			field:  "Password",
			reason: "value length must be between 8 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return LoginRequestMultiError(errors)
	}

	return nil
}

// LoginRequestMultiError is an error wrapping multiple validation errors
// returned by LoginRequest.ValidateAll() if the designated constraints aren't met.
type LoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginRequestMultiError) AllErrors() []error { return m }

// LoginRequestValidationError is the validation error returned by
// LoginRequest.Validate if the designated constraints aren't met.
type LoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginRequestValidationError) ErrorName() string { return "LoginRequestValidationError" }

// Error satisfies the builtin error interface
func (e LoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginRequestValidationError{}

var _LoginRequest_Phone_Pattern = regexp.MustCompile("^\\+[1-9]\\d{1,14}$")

// Validate checks the field values on TokenPair with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TokenPair) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TokenPair with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TokenPairMultiError, or nil
// if none found.
func (m *TokenPair) ValidateAll() error {
	return m.validate(true)
}

func (m *TokenPair) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccessToken

	// no validation rules for RefreshToken

	if len(errors) > 0 {
		return TokenPairMultiError(errors)
	}

	return nil
}

// TokenPairMultiError is an error wrapping multiple validation errors returned
// by TokenPair.ValidateAll() if the designated constraints aren't met.
type TokenPairMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TokenPairMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TokenPairMultiError) AllErrors() []error { return m }

// TokenPairValidationError is the validation error returned by
// TokenPair.Validate if the designated constraints aren't met.
type TokenPairValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TokenPairValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TokenPairValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TokenPairValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TokenPairValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TokenPairValidationError) ErrorName() string { return "TokenPairValidationError" }

// Error satisfies the builtin error interface
func (e TokenPairValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTokenPair.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TokenPairValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TokenPairValidationError{}

// Validate checks the field values on RefreshRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RefreshRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RefreshRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RefreshRequestMultiError,
// or nil if none found.
func (m *RefreshRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RefreshRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetRefreshToken()) < 16 {
		err := RefreshRequestValidationError{
			field:  "RefreshToken",
			reason: "value length must be at least 16 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RefreshRequestMultiError(errors)
	}

	return nil
}

// RefreshRequestMultiError is an error wrapping multiple validation errors
// returned by RefreshRequest.ValidateAll() if the designated constraints
// aren't met.
type RefreshRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RefreshRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RefreshRequestMultiError) AllErrors() []error { return m }

// RefreshRequestValidationError is the validation error returned by
// RefreshRequest.Validate if the designated constraints aren't met.
type RefreshRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RefreshRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RefreshRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RefreshRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RefreshRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RefreshRequestValidationError) ErrorName() string { return "RefreshRequestValidationError" }

// Error satisfies the builtin error interface
func (e RefreshRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRefreshRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RefreshRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RefreshRequestValidationError{}

// Validate checks the field values on ValidateAccessTokenRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ValidateAccessTokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ValidateAccessTokenRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ValidateAccessTokenRequestMultiError, or nil if none found.
func (m *ValidateAccessTokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ValidateAccessTokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetAccessToken()) < 16 {
		err := ValidateAccessTokenRequestValidationError{
			field:  "AccessToken",
			reason: "value length must be at least 16 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ValidateAccessTokenRequestMultiError(errors)
	}

	return nil
}

// ValidateAccessTokenRequestMultiError is an error wrapping multiple
// validation errors returned by ValidateAccessTokenRequest.ValidateAll() if
// the designated constraints aren't met.
type ValidateAccessTokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ValidateAccessTokenRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ValidateAccessTokenRequestMultiError) AllErrors() []error { return m }

// ValidateAccessTokenRequestValidationError is the validation error returned
// by ValidateAccessTokenRequest.Validate if the designated constraints aren't met.
type ValidateAccessTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ValidateAccessTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ValidateAccessTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ValidateAccessTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ValidateAccessTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ValidateAccessTokenRequestValidationError) ErrorName() string {
	return "ValidateAccessTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ValidateAccessTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sValidateAccessTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ValidateAccessTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ValidateAccessTokenRequestValidationError{}

// Validate checks the field values on ValidateAccessTokenResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ValidateAccessTokenResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ValidateAccessTokenResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ValidateAccessTokenResponseMultiError, or nil if none found.
func (m *ValidateAccessTokenResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ValidateAccessTokenResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Valid

	if len(errors) > 0 {
		return ValidateAccessTokenResponseMultiError(errors)
	}

	return nil
}

// ValidateAccessTokenResponseMultiError is an error wrapping multiple
// validation errors returned by ValidateAccessTokenResponse.ValidateAll() if
// the designated constraints aren't met.
type ValidateAccessTokenResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ValidateAccessTokenResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ValidateAccessTokenResponseMultiError) AllErrors() []error { return m }

// ValidateAccessTokenResponseValidationError is the validation error returned
// by ValidateAccessTokenResponse.Validate if the designated constraints
// aren't met.
type ValidateAccessTokenResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ValidateAccessTokenResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ValidateAccessTokenResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ValidateAccessTokenResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ValidateAccessTokenResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ValidateAccessTokenResponseValidationError) ErrorName() string {
	return "ValidateAccessTokenResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ValidateAccessTokenResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sValidateAccessTokenResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ValidateAccessTokenResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ValidateAccessTokenResponseValidationError{}

// Validate checks the field values on RequestPasswordResetRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RequestPasswordResetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RequestPasswordResetRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RequestPasswordResetRequestMultiError, or nil if none found.
func (m *RequestPasswordResetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RequestPasswordResetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_RequestPasswordResetRequest_Phone_Pattern.MatchString(m.GetPhone()) {
		err := RequestPasswordResetRequestValidationError{
			field:  "Phone",
			reason: "value does not match regex pattern \"^\\\\+[1-9]\\\\d{1,14}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RequestPasswordResetRequestMultiError(errors)
	}

	return nil
}

// RequestPasswordResetRequestMultiError is an error wrapping multiple
// validation errors returned by RequestPasswordResetRequest.ValidateAll() if
// the designated constraints aren't met.
type RequestPasswordResetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RequestPasswordResetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RequestPasswordResetRequestMultiError) AllErrors() []error { return m }

// RequestPasswordResetRequestValidationError is the validation error returned
// by RequestPasswordResetRequest.Validate if the designated constraints
// aren't met.
type RequestPasswordResetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RequestPasswordResetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RequestPasswordResetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RequestPasswordResetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RequestPasswordResetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RequestPasswordResetRequestValidationError) ErrorName() string {
	return "RequestPasswordResetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RequestPasswordResetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRequestPasswordResetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RequestPasswordResetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RequestPasswordResetRequestValidationError{}

var _RequestPasswordResetRequest_Phone_Pattern = regexp.MustCompile("^\\+[1-9]\\d{1,14}$")

// Validate checks the field values on ConfirmPasswordResetRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ConfirmPasswordResetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConfirmPasswordResetRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConfirmPasswordResetRequestMultiError, or nil if none found.
func (m *ConfirmPasswordResetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ConfirmPasswordResetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_ConfirmPasswordResetRequest_Phone_Pattern.MatchString(m.GetPhone()) {
		err := ConfirmPasswordResetRequestValidationError{
			field:  "Phone",
			reason: "value does not match regex pattern \"^\\\\+[1-9]\\\\d{1,14}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetToken()) < 16 {
		err := ConfirmPasswordResetRequestValidationError{
			field:  "Token",
			reason: "value length must be at least 16 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetNewPassword()); l < 8 || l > 64 {
		err := ConfirmPasswordResetRequestValidationError{
			field:  "NewPassword",
			reason: "value length must be between 8 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ConfirmPasswordResetRequestMultiError(errors)
	}

	return nil
}

// ConfirmPasswordResetRequestMultiError is an error wrapping multiple
// validation errors returned by ConfirmPasswordResetRequest.ValidateAll() if
// the designated constraints aren't met.
type ConfirmPasswordResetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConfirmPasswordResetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConfirmPasswordResetRequestMultiError) AllErrors() []error { return m }

// ConfirmPasswordResetRequestValidationError is the validation error returned
// by ConfirmPasswordResetRequest.Validate if the designated constraints
// aren't met.
type ConfirmPasswordResetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfirmPasswordResetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfirmPasswordResetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfirmPasswordResetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfirmPasswordResetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfirmPasswordResetRequestValidationError) ErrorName() string {
	return "ConfirmPasswordResetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ConfirmPasswordResetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConfirmPasswordResetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfirmPasswordResetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfirmPasswordResetRequestValidationError{}

var _ConfirmPasswordResetRequest_Phone_Pattern = regexp.MustCompile("^\\+[1-9]\\d{1,14}$")

// Validate checks the field values on LogoutRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LogoutRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LogoutRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LogoutRequestMultiError, or
// nil if none found.
func (m *LogoutRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LogoutRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetRefreshToken()) < 16 {
		err := LogoutRequestValidationError{
			field:  "RefreshToken",
			reason: "value length must be at least 16 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return LogoutRequestMultiError(errors)
	}

	return nil
}

// LogoutRequestMultiError is an error wrapping multiple validation errors
// returned by LogoutRequest.ValidateAll() if the designated constraints
// aren't met.
type LogoutRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogoutRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogoutRequestMultiError) AllErrors() []error { return m }

// LogoutRequestValidationError is the validation error returned by
// LogoutRequest.Validate if the designated constraints aren't met.
type LogoutRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogoutRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogoutRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogoutRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogoutRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogoutRequestValidationError) ErrorName() string { return "LogoutRequestValidationError" }

// Error satisfies the builtin error interface
func (e LogoutRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogoutRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogoutRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogoutRequestValidationError{}
