// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: auth/v1/auth.proto

package authv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Назначение кода подтверждения (соответствует БД)
type VerificationPurpose int32

const (
	VerificationPurpose_VERIFICATION_PURPOSE_UNSPECIFIED  VerificationPurpose = 0
	VerificationPurpose_VERIFICATION_PURPOSE_SIGNUP       VerificationPurpose = 1
	VerificationPurpose_VERIFICATION_PURPOSE_CHANGE_PHONE VerificationPurpose = 2
)

// Enum value maps for VerificationPurpose.
var (
	VerificationPurpose_name = map[int32]string{
		0: "VERIFICATION_PURPOSE_UNSPECIFIED",
		1: "VERIFICATION_PURPOSE_SIGNUP",
		2: "VERIFICATION_PURPOSE_CHANGE_PHONE",
	}
	VerificationPurpose_value = map[string]int32{
		"VERIFICATION_PURPOSE_UNSPECIFIED":  0,
		"VERIFICATION_PURPOSE_SIGNUP":       1,
		"VERIFICATION_PURPOSE_CHANGE_PHONE": 2,
	}
)

func (x VerificationPurpose) Enum() *VerificationPurpose {
	p := new(VerificationPurpose)
	*p = x
	return p
}

func (x VerificationPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (VerificationPurpose) Type() protoreflect.EnumType {
	return &file_auth_v1_auth_proto_enumTypes[0]
}

func (x VerificationPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationPurpose.Descriptor instead.
func (VerificationPurpose) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

type CreateTelegramVerificationCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Telegram user ID (обязателен)
	TelegramId int64 `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	// Назначение кода (signup/change_phone)
	Purpose VerificationPurpose `protobuf:"varint,2,opt,name=purpose,proto3,enum=auth.v1.VerificationPurpose" json:"purpose,omitempty"`
	// Телефон в формате E.164; для signup обычно обязателен на вашей стороне
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	// TTL в секундах (по умолчанию 300 на сервере)
	TtlSeconds    uint32 `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTelegramVerificationCodeRequest) Reset() {
	*x = CreateTelegramVerificationCodeRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTelegramVerificationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTelegramVerificationCodeRequest) ProtoMessage() {}

func (x *CreateTelegramVerificationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTelegramVerificationCodeRequest.ProtoReflect.Descriptor instead.
func (*CreateTelegramVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTelegramVerificationCodeRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *CreateTelegramVerificationCodeRequest) GetPurpose() VerificationPurpose {
	if x != nil {
		return x.Purpose
	}
	return VerificationPurpose_VERIFICATION_PURPOSE_UNSPECIFIED
}

func (x *CreateTelegramVerificationCodeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateTelegramVerificationCodeRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreateTelegramVerificationCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Одноразовый код в явном виде (если требуется отправлять ботом)
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Время истечения
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTelegramVerificationCodeResponse) Reset() {
	*x = CreateTelegramVerificationCodeResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTelegramVerificationCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTelegramVerificationCodeResponse) ProtoMessage() {}

func (x *CreateTelegramVerificationCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTelegramVerificationCodeResponse.ProtoReflect.Descriptor instead.
func (*CreateTelegramVerificationCodeResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTelegramVerificationCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateTelegramVerificationCodeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ConfirmTelegramVerificationRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TelegramId int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	Purpose    VerificationPurpose    `protobuf:"varint,2,opt,name=purpose,proto3,enum=auth.v1.VerificationPurpose" json:"purpose,omitempty"`
	// Код, введённый/полученный пользователем
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// Телефон в E.164 — помогает связать с ожидаемой операцией (signup/change)
	Phone         string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmTelegramVerificationRequest) Reset() {
	*x = ConfirmTelegramVerificationRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmTelegramVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTelegramVerificationRequest) ProtoMessage() {}

func (x *ConfirmTelegramVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTelegramVerificationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmTelegramVerificationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmTelegramVerificationRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *ConfirmTelegramVerificationRequest) GetPurpose() VerificationPurpose {
	if x != nil {
		return x.Purpose
	}
	return VerificationPurpose_VERIFICATION_PURPOSE_UNSPECIFIED
}

func (x *ConfirmTelegramVerificationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ConfirmTelegramVerificationRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ConfirmTelegramVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Verified      bool                   `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmTelegramVerificationResponse) Reset() {
	*x = ConfirmTelegramVerificationResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmTelegramVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTelegramVerificationResponse) ProtoMessage() {}

func (x *ConfirmTelegramVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTelegramVerificationResponse.ProtoReflect.Descriptor instead.
func (*ConfirmTelegramVerificationResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmTelegramVerificationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConfirmTelegramVerificationResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ConfirmTelegramVerificationResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TokenPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *TokenPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ValidateAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessTokenRequest) Reset() {
	*x = ValidateAccessTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessTokenRequest) ProtoMessage() {}

func (x *ValidateAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateAccessTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessTokenResponse) Reset() {
	*x = ValidateAccessTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessTokenResponse) ProtoMessage() {}

func (x *ValidateAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateAccessTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateAccessTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type RequestPasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPasswordResetRequest) Reset() {
	*x = RequestPasswordResetRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPasswordResetRequest) ProtoMessage() {}

func (x *RequestPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*RequestPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *RequestPasswordResetRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ConfirmPasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPasswordResetRequest) Reset() {
	*x = ConfirmPasswordResetRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPasswordResetRequest) ProtoMessage() {}

func (x *ConfirmPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *ConfirmPasswordResetRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ConfirmPasswordResetRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConfirmPasswordResetRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"\xf0\x01\n" +
	"%CreateTelegramVerificationCodeRequest\x12(\n" +
	"\vtelegram_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"telegramId\x12@\n" +
	"\apurpose\x18\x02 \x01(\x0e2\x1c.auth.v1.VerificationPurposeB\b\xfaB\x05\x82\x01\x02\x10\x01R\apurpose\x12.\n" +
	"\x05phone\x18\x03 \x01(\tB\x18\xfaB\x15r\x132\x11^\\+[1-9]\\d{1,14}$R\x05phone\x12+\n" +
	"\vttl_seconds\x18\x04 \x01(\rB\n" +
	"\xfaB\a*\x05\x18\x90\x1c(<R\n" +
	"ttlSeconds\"\x82\x01\n" +
	"&CreateTelegramVerificationCodeResponse\x12\x1d\n" +
	"\x04code\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18\fR\x04code\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xdf\x01\n" +
	"\"ConfirmTelegramVerificationRequest\x12(\n" +
	"\vtelegram_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"telegramId\x12@\n" +
	"\apurpose\x18\x02 \x01(\x0e2\x1c.auth.v1.VerificationPurposeB\b\xfaB\x05\x82\x01\x02\x10\x01R\apurpose\x12\x1d\n" +
	"\x04code\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18\fR\x04code\x12.\n" +
	"\x05phone\x18\x04 \x01(\tB\x18\xfaB\x15r\x132\x11^\\+[1-9]\\d{1,14}$R\x05phone\"p\n" +
	"#ConfirmTelegramVerificationResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1a\n" +
	"\bverified\x18\x03 \x01(\bR\bverified\"h\n" +
	"\x0fRegisterRequest\x12.\n" +
	"\x05phone\x18\x01 \x01(\tB\x18\xfaB\x15r\x132\x11^\\+[1-9]\\d{1,14}$R\x05phone\x12%\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\b\x18@R\bpassword\"8\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"e\n" +
	"\fLoginRequest\x12.\n" +
	"\x05phone\x18\x01 \x01(\tB\x18\xfaB\x15r\x132\x11^\\+[1-9]\\d{1,14}$R\x05phone\x12%\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\b\x18@R\bpassword\"S\n" +
	"\tTokenPair\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\">\n" +
	"\x0eRefreshRequest\x12,\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x10R\frefreshToken\"H\n" +
	"\x1aValidateAccessTokenRequest\x12*\n" +
	"\faccess_token\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x10R\vaccessToken\"L\n" +
	"\x1bValidateAccessTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\"M\n" +
	"\x1bRequestPasswordResetRequest\x12.\n" +
	"\x05phone\x18\x01 \x01(\tB\x18\xfaB\x15r\x132\x11^\\+[1-9]\\d{1,14}$R\x05phone\"\x9a\x01\n" +
	"\x1bConfirmPasswordResetRequest\x12.\n" +
	"\x05phone\x18\x01 \x01(\tB\x18\xfaB\x15r\x132\x11^\\+[1-9]\\d{1,14}$R\x05phone\x12\x1d\n" +
	"\x05token\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x10R\x05token\x12,\n" +
	"\fnew_password\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\b\x18@R\vnewPassword\"=\n" +
	"\rLogoutRequest\x12,\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x10R\frefreshToken*\x83\x01\n" +
	"\x13VerificationPurpose\x12$\n" +
	" VERIFICATION_PURPOSE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bVERIFICATION_PURPOSE_SIGNUP\x10\x01\x12%\n" +
	"!VERIFICATION_PURPOSE_CHANGE_PHONE\x10\x022\xe4\b\n" +
	"\vAuthService\x12a\n" +
	"\bRegister\x12\x18.auth.v1.RegisterRequest\x1a\x19.auth.v1.RegisterResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/register\x12Q\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x12.auth.v1.TokenPair\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12W\n" +
	"\aRefresh\x12\x17.auth.v1.RefreshRequest\x1a\x12.auth.v1.TokenPair\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/refresh\x12\x89\x01\n" +
	"\x13ValidateAccessToken\x12#.auth.v1.ValidateAccessTokenRequest\x1a$.auth.v1.ValidateAccessTokenResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/auth/validate-access\x12\xaf\x01\n" +
	"\x1eCreateTelegramVerificationCode\x12..auth.v1.CreateTelegramVerificationCodeRequest\x1a/.auth.v1.CreateTelegramVerificationCodeResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v1/auth/telegram/code:create\x12\xa2\x01\n" +
	"\x1bConfirmTelegramVerification\x12+.auth.v1.ConfirmTelegramVerificationRequest\x1a,.auth.v1.ConfirmTelegramVerificationResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/auth/telegram/confirm\x12\x84\x01\n" +
	"\x14RequestPasswordReset\x12$.auth.v1.RequestPasswordResetRequest\x1a\x16.google.protobuf.Empty\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/auth/password/reset/request\x12\x84\x01\n" +
	"\x14ConfirmPasswordReset\x12$.auth.v1.ConfirmPasswordResetRequest\x1a\x16.google.protobuf.Empty\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/auth/password/reset/confirm\x12U\n" +
	"\x06Logout\x12\x16.auth.v1.LogoutRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x13/api/v1/auth/logoutB7Z5github.com/Anabol1ks/rentAdvisor-proto/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_auth_v1_auth_proto_goTypes = []any{
	(VerificationPurpose)(0),                       // 0: auth.v1.VerificationPurpose
	(*CreateTelegramVerificationCodeRequest)(nil),  // 1: auth.v1.CreateTelegramVerificationCodeRequest
	(*CreateTelegramVerificationCodeResponse)(nil), // 2: auth.v1.CreateTelegramVerificationCodeResponse
	(*ConfirmTelegramVerificationRequest)(nil),     // 3: auth.v1.ConfirmTelegramVerificationRequest
	(*ConfirmTelegramVerificationResponse)(nil),    // 4: auth.v1.ConfirmTelegramVerificationResponse
	(*RegisterRequest)(nil),                        // 5: auth.v1.RegisterRequest
	(*RegisterResponse)(nil),                       // 6: auth.v1.RegisterResponse
	(*LoginRequest)(nil),                           // 7: auth.v1.LoginRequest
	(*TokenPair)(nil),                              // 8: auth.v1.TokenPair
	(*RefreshRequest)(nil),                         // 9: auth.v1.RefreshRequest
	(*ValidateAccessTokenRequest)(nil),             // 10: auth.v1.ValidateAccessTokenRequest
	(*ValidateAccessTokenResponse)(nil),            // 11: auth.v1.ValidateAccessTokenResponse
	(*RequestPasswordResetRequest)(nil),            // 12: auth.v1.RequestPasswordResetRequest
	(*ConfirmPasswordResetRequest)(nil),            // 13: auth.v1.ConfirmPasswordResetRequest
	(*LogoutRequest)(nil),                          // 14: auth.v1.LogoutRequest
	(*timestamppb.Timestamp)(nil),                  // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                          // 16: google.protobuf.Empty
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	0,  // 0: auth.v1.CreateTelegramVerificationCodeRequest.purpose:type_name -> auth.v1.VerificationPurpose
	15, // 1: auth.v1.CreateTelegramVerificationCodeResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 2: auth.v1.ConfirmTelegramVerificationRequest.purpose:type_name -> auth.v1.VerificationPurpose
	5,  // 3: auth.v1.AuthService.Register:input_type -> auth.v1.RegisterRequest
	7,  // 4: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	9,  // 5: auth.v1.AuthService.Refresh:input_type -> auth.v1.RefreshRequest
	10, // 6: auth.v1.AuthService.ValidateAccessToken:input_type -> auth.v1.ValidateAccessTokenRequest
	1,  // 7: auth.v1.AuthService.CreateTelegramVerificationCode:input_type -> auth.v1.CreateTelegramVerificationCodeRequest
	3,  // 8: auth.v1.AuthService.ConfirmTelegramVerification:input_type -> auth.v1.ConfirmTelegramVerificationRequest
	12, // 9: auth.v1.AuthService.RequestPasswordReset:input_type -> auth.v1.RequestPasswordResetRequest
	13, // 10: auth.v1.AuthService.ConfirmPasswordReset:input_type -> auth.v1.ConfirmPasswordResetRequest
	14, // 11: auth.v1.AuthService.Logout:input_type -> auth.v1.LogoutRequest
	6,  // 12: auth.v1.AuthService.Register:output_type -> auth.v1.RegisterResponse
	8,  // 13: auth.v1.AuthService.Login:output_type -> auth.v1.TokenPair
	8,  // 14: auth.v1.AuthService.Refresh:output_type -> auth.v1.TokenPair
	11, // 15: auth.v1.AuthService.ValidateAccessToken:output_type -> auth.v1.ValidateAccessTokenResponse
	2,  // 16: auth.v1.AuthService.CreateTelegramVerificationCode:output_type -> auth.v1.CreateTelegramVerificationCodeResponse
	4,  // 17: auth.v1.AuthService.ConfirmTelegramVerification:output_type -> auth.v1.ConfirmTelegramVerificationResponse
	16, // 18: auth.v1.AuthService.RequestPasswordReset:output_type -> google.protobuf.Empty
	16, // 19: auth.v1.AuthService.ConfirmPasswordReset:output_type -> google.protobuf.Empty
	16, // 20: auth.v1.AuthService.Logout:output_type -> google.protobuf.Empty
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
